<?php
declare(strict_types=1);
header('Content-Type: text/html; charset=UTF-8');
const PAGE_TOKEN='ALFA-SEC-2025';const BASEROW_BASE='https://base.alfagolden.com';const BASEROW_TABLE=704;const BASEROW_TOKEN='h5qAt85gtiJDAzpH51WrXPywhmnhrPWy';const WEBHOOK_URL='https://n8n.alfagolden.com/webhook-test/alfa-doc';const FIELD_QUOTE_NO='field_6783';const FIELD_CLIENT='field_6977';const FIELD_TOTAL='field_6984';const FIELD_DATE='field_6789';
function ensure_token():void{$tok=(string)($_GET['token']??$_POST['token']??'');if($tok!==PAGE_TOKEN){http_response_code(401);header('Content-Type: application/json; charset=UTF-8');echo json_encode(['ok'=>false,'error'=>'UNAUTHORIZED'],JSON_UNESCAPED_UNICODE);exit;}}
function http_post_json(string $url,array $payload,array $headers=[]):array{$headers=array_merge(['Content-Type: application/json'],$headers);$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_CONNECTTIMEOUT=>15,CURLOPT_TIMEOUT=>30,CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),CURLOPT_HTTPHEADER=>$headers]);$raw=curl_exec($ch);$err=curl_error($ch);$code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);if($raw===false)throw new RuntimeException("HTTP POST error: $err");$data=json_decode($raw,true);if($code>=400)throw new RuntimeException("HTTP $code: ".($data?json_encode($data,JSON_UNESCAPED_UNICODE):$raw));return is_array($data)?$data:['raw'=>$raw];}
function http_json(string $url,array $headers=[]):array{$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_CONNECTTIMEOUT=>15,CURLOPT_TIMEOUT=>30,CURLOPT_HTTPHEADER=>$headers]);$raw=curl_exec($ch);$err=curl_error($ch);$code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);if($raw===false)throw new RuntimeException("HTTP error: $err");$data=json_decode($raw,true);if(!is_array($data))throw new RuntimeException("Bad JSON (HTTP $code): ".substr($raw,0,300));if($code>=400)throw new RuntimeException("HTTP $code: ".json_encode($data,JSON_UNESCAPED_UNICODE));return $data;}
function baserow_rows(int $page=1,int $size=100):array{$qs=http_build_query(['user_field_names'=>'false','page'=>max(1,$page),'size'=>min(200,max(1,$size))]);$url=rtrim(BASEROW_BASE,'/')."/api/database/rows/table/".BASEROW_TABLE."/?$qs";$hdr=["Authorization: Token ".BASEROW_TOKEN,"Accept: application/json"];return http_json($url,$hdr);}
function val($row,string $field){return$row[$field]??null;}
function link_row_text($value):string{if(!is_array($value)||empty($value))return'';$first=$value[0];if(is_array($first)&&array_key_exists('value',$first))return(string)($first['value']??'');return'';}
function fmt_price($n):string{if($n===null||$n==='')return'-';return number_format((float)$n);}
function fmt_date($s):string{if(!$s)return'-';try{return(new DateTime((string)$s))->format('Y-m-d');}catch(Throwable $e){return(string)$s;}}
function sanitize_int_id($v):int{if(is_int($v))return$v;if(is_string($v)&&ctype_digit($v))return(int)$v;throw new InvalidArgumentException('Invalid id');}
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'&&($_POST['action']??'')==='fire_webhook'){try{ensure_token();$id=isset($_POST['id'])?sanitize_int_id($_POST['id']):null;if($id===null)throw new InvalidArgumentException('Missing id');$resp=http_post_json(WEBHOOK_URL,['id'=>$id]);header('Content-Type: application/json; charset=UTF-8');echo json_encode(['ok'=>true,'sent'=>['id'=>$id],'webhook_response'=>$resp],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);}catch(Throwable $e){http_response_code(500);header('Content-Type: application/json; charset=UTF-8');echo json_encode(['ok'=>false,'error'=>$e->getMessage()],JSON_UNESCAPED_UNICODE);}exit;}
try{ensure_token();$page=isset($_GET['page'])&&ctype_digit((string)$_GET['page'])?(int)$_GET['page']:1;$rows=(baserow_rows($page,100)['results']??[]);}catch(Throwable $e){http_response_code(500);header('Content-Type: text/plain; charset=UTF-8');echo "Error: ".$e->getMessage();exit;}
?>
<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>عروض الأسعار</title><style>body{font-family:system-ui,sans-serif;background:#f8f9fa;margin:20px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:16px}table{width:100%;border-collapse:collapse}th,td{padding:10px 12px;border-bottom:1px solid #eee;text-align:right}th{background:#fafafa}.btn{border:0;padding:8px 10px;border-radius:8px;cursor:pointer;font-weight:600}.btn-send{background:#977e2b;color:#fff}.btn-send:disabled{opacity:.5}.msg{margin:10px 0;padding:10px;border-radius:8px;display:none}.msg.ok{background:#e8f5e9;color:#1b5e20}.msg.err{background:#ffebee;color:#b71c1c}</style></head><body><div class="card"><h2>عروض الأسعار</h2><div id="msgOk" class="msg ok"></div><div id="msgErr" class="msg err"></div><table><thead><tr><th>#</th><th>رقم العرض</th><th>العميل</th><th>الإجمالي</th><th>التاريخ</th><th>Webhook</th></tr></thead><tbody><?php if(empty($rows)): ?><tr><td colspan="6">لا توجد بيانات.</td></tr><?php else: foreach($rows as $r): $rid=val($r,'id');$qno=val($r,FIELD_QUOTE_NO);$client=link_row_text(val($r,FIELD_CLIENT));$total=fmt_price(val($r,FIELD_TOTAL));$date=fmt_date(val($r,FIELD_DATE));?><tr><td><?= (int)$rid ?></td><td><?= htmlspecialchars((string)$qno) ?></td><td><?= htmlspecialchars($client) ?></td><td><?= htmlspecialchars($total) ?></td><td><?= htmlspecialchars($date) ?></td><td><button class="btn btn-send" onclick="sendHook(<?= (int)$rid ?>, this)">أرسل</button></td></tr><?php endforeach; endif; ?></tbody></table></div><script>const PAGE_TOKEN='<?= PAGE_TOKEN ?>';function show(el,text){el.textContent=text;el.style.display='block';setTimeout(()=>{el.style.display='none'},4000)}async function sendHook(id,btn){if(!id)return;const ok=document.getElementById('msgOk');const err=document.getElementById('msgErr');btn.disabled=true;try{const form=new FormData();form.append('action','fire_webhook');form.append('token',PAGE_TOKEN);form.append('id',String(id));const res=await fetch(location.pathname,{method:'POST',body:form});const js=await res.json().catch(()=>({}));if(!res.ok||!js||js.ok===false){throw new Error(js&&js.error?js.error:'Failed')}show(ok,'تم الإرسال بنجاح (id='+id+')')}catch(e){show(err,'فشل: '+(e.message||e))}finally{btn.disabled=false}}</script></body></html>
